cache:
  directories:
  - $HOME/.m2/repository

git:
  depth: 3

jdk:
- openjdk8
- oraclejdk8

install: mvn install -DskipTests=true -V -Pfeature-truelicense-v1

language: java

script: mvn verify -Pfeature-truelicense-v1
