cache:
  directories:
  - $HOME/.m2/repository

git:
  depth: 3

jdk:
- openjdk8
- oraclejdk8

language: java

install: mvn install -DskipTests=true -Pfeature-truelicense-v1

script: mvn verify -Pfeature-truelicense-v1
