cache:
  directories:
  - $HOME/.m2/repository

git:
  depth: 3

jdk:
- openjdk8
- oraclejdk8

install: mvn -V -DskipTests=true -Pfeature-truelicense-v1 install

language: java

script: mvn -Pfeature-truelicense-v1 verify
