cache:
  directories:
  - $HOME/.m2/repository

jdk:
- openjdk8
- openjdk9
- openjdk10
- openjdk11

install: ./mvnw -V -DskipTests=true -Dgpg.skip=true -Psonatype-oss-release install

language: java

script: ./mvnw verify
