cache:
  directories:
  - $HOME/.m2/repository

jdk:
- openjdk8
- oraclejdk8
- oraclejdk9

install: ./mvnw -V -DskipTests=true -Dgpg.skip=true -Psonatype-oss-release install

language: java

script: ./mvnw verify
