addons:
  apt:
    packages:
    - openjdk-6-jdk

cache:
  directories:
  - $HOME/.m2/repository

git:
  depth: 3

jdk:
- openjdk6
- openjdk7
- openjdk8
- oraclejdk8

language: java

script: mvn verify -B
